node {
    try {
        deleteDir()
        def dockerImage
        def buildDir="yaml-cpp/build"

        stage('Prepare environment') {
            checkout scm
            dockerImage = docker.build("yaml-cpp-builder:0.1", "./5-jenkins-pipeline")
            sh "git clone --depth 1 https://github.com/jbeder/yaml-cpp.git"
            sh "mkdir yaml-cpp/build"
        }

        stage('Build') {
            dockerImage.inside("--rm --cap-drop=all --memory=2g --cpus=2 -v ${WORKSPACE}/yaml-cpp:/yaml-cpp") {
                dir(buildDir){
                    sh "cmake .. && make"
                }
            }
        }

        stage('Archive artifact') {
            sh """
            VERSION=\$(cat $buildDir/yaml-cpp.pc | grep "Version" | cut -d ' ' -f 2)
            tar -zcvf yaml-cpp-\$VERSION.tar.gz $buildDir
            """
            archiveArtifacts artifacts: '*.tar.gz'
        }

    } catch (e) {
        echo 'Build failed'
        throw e
    } finally {
        deleteDir()
    }
}   

